# Generated by Django 2.1.7 on 2019-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='hour_visit',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
